f1tenth:
  joy_teleop:
    ros__parameters:
      # Enable Human control by holding Left Bumper
      human_control:
        type: topic
        interface_type: ackermann_msgs/msg/AckermannDriveStamped
        topic_name: ackermann_cmd
        deadman_buttons: [4]
        axis_mappings:
          drive-speed:
            axis: 1
            scale: 5.0
            offset: 0.0
          drive-steering_angle:
            axis: 2
            scale: 0.34
            offset: 0.0
  
      emergency_brake:
        type: topic
        interface_type: ackermann_msgs/msg/AckermannDriveStamped
        topic_name: ackermann_cmd
        deadman_buttons: [5]
        message_value:
          drive-speed:
            value: 0.0
          drive-steering_angle:
            value: 0.0