f1tenth:
  throttle_interpolator:
      ros__parameters:
        rpm_input_topic: '/f1tenth/commands/motor/unsmoothed_speed'
        rpm_output_topic: '/f1tenth/commands/motor/speed'
        servo_input_topic: '/f1tenth/commands/servo/unsmoothed_position' 
        servo_output_topic: '/f1tenth/commands/servo/position'
        # servo smoother - limits acceleration and smooths anything above limit
        max_acceleration: 2.5 # meters/second^2
        throttle_smoother_rate: 75.0 # messages/sec
        speed_max: 23250
        speed_min: -23250
        # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
        speed_to_erpm_gain: 7685.0
        speed_to_erpm_offset: 0.0
        steering_angle_to_servo_gain: -1.2135
        steering_angle_to_servo_offset: 0.4533
        # servo smoother - limits rotation speed and smooths anything above limit
        max_servo_speed: 3.2 # radians/second
        servo_smoother_rate: 75.0 # messages/sec
        servo_min: 0.15
        servo_max: 0.85
  ackermann_to_vesc:
      ros__parameters:
        # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
        speed_to_erpm_gain: 7685.0
        speed_to_erpm_offset: 0.0
        steering_angle_to_servo_gain: -1.2135
        steering_angle_to_servo_offset: 0.4533
  vesc_driver:
      ros__parameters:
        port: /dev/sensors/vesc
        duty_cycle_min: 0.0
        duty_cycle_max: 0.0
        current_min: 0.0
        current_max: 100.0
        brake_min: -20000.0
        brake_max: 200000.0
        speed_min: -23250.0
        speed_max: 23250.0
        position_min: 0.0
        position_max: 0.0
        servo_min: 0.15
        servo_max: 0.85
  vesc_to_odom:
      ros__parameters:
        odom_frame: odom
        base_frame: base_link
        speed_to_erpm_gain: 7685.0
        speed_to_erpm_offset: 0.0
        use_servo_cmd_to_calc_angular_velocity: false
        steering_angle_to_servo_gain: -1.2135
        steering_angle_to_servo_offset: 0.4533
        wheelbase: 0.2
        publish_tf: true
  urg_node:
      ros__parameters:
        angle_max: 3.14
        angle_min: -3.14
        ip_address: "192.168.0.10"
        ip_port: 10940
        serial_baud: 115200
        laser_frame_id: "laser"
        calibrate_time: false
        default_user_latency: 0.0
        diagnostics_tolerance: 0.05
        diagnostics_window_time: 5.0
        error_limit: 4
        get_detailed_status: false
        publish_intensity: false
        publish_multiecho: false
        cluster: 1
        skip: 0

