throttle_interpolator:
    ros__parameters:
      rpm_input_topic: '/f1tenth/commands/motor/unsmoothed_speed'
      rpm_output_topic: '/f1tenth/commands/motor/speed'
      servo_input_topic: '/f1tenth/commands/servo/unsmoothed_position' 
      servo_output_topic: '/f1tenth/commands/servo/position'
      # servo smoother - limits acceleration and smooths anything above limit
      max_acceleration: 2.5 # meters/second^2
      throttle_smoother_rate: 75.0 # messages/sec
      speed_max: 23250
      speed_min: -23250
      # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
      speed_to_erpm_gain: 7685
      # servo smoother - limits rotation speed and smooths anything above limit
      max_servo_speed: 3.2 # radians/second
      steering_angle_to_servo_gain: -1.2135
      servo_smoother_rate: 75.0 # messages/sec
      servo_min: 0.15
      servo_max: 0.85
      steering_angle_to_servo_offset: 0.4533
